# Document Information
#+TITLE: Foreign Pol. Decision Making
#+AUTHOR: Sudhan Chitgopkar
#+EMAIL: sudhanchitgopkar@uga.edu
* 02.08.21
- When we frame outcomes in terms of gains, we tend to be risk-averse, even when the gambles are objectively better
- When we frame outcomes in terms of losses, we tend to be risk-acceptant in order to avoid larger losses, even when the gambles are objectively worse for us
- This can often be seen in stock market crashes and stock behavior, wherein people sell during a stock downturn when the rational decision is to hold on to the stock
  - This can further be seen with (1) Carter and the Iranian Hostage Crisis, (2) The 2016 election of Trump, the 2020 election of Biden
- To remove yourself from a frame (regardless of whether it is risk-averse or risk-acceptant), it is critical to consider both benefits and losses
* 02.05.21
** Loss Aversion & Policy
- Argues that policies are either loss averting or gain seeking
  - Berejikian argues against this
  - Any policy can be reframed to be either loss avoiding or gain seeking
- Public is more favorable towards policies that are loss avoiding
* 02.03.21
** Concession Aversion
- Because of loss aversion, anything given up in a negotiation has an inflated value.
- Because this is true for both sides of a negotiation, there is a permanent hurdle to achieving a negotiated settlement
- Also known as the endowment effect
- concession aversion and loss aversion is stronger when bad behavior has started
  - It is harder to stop behavior that has already been started than it is to pre-empt bad behavior
- Due to loss aversion, states often double down on their failed policies and don't correct course
- Empirically, great powers always decline and hasten that decline by trying to hold fast to their previous status
  - Great powers can either try harder to hold on to their power and influence
 - or great powers can accept their declining status and recalibrate their policies accordingly
* 02.01.21
** Loss Aversion
- Consider a simple dilemma, wherein an actor chooses whether to play a game.
  - A fair coin is flipped
  - If the coin is heads, the actor recieves $125
  - If the coin is tails, the actor loses $125
- This dilemma has an EV of (0.5 * 125) + (0.5 * -125) = 0
- Despite an EV of 0, the vast majority of people would not play this game
- This is a result of loss aversion, people cognitively weigh losses and harms more than they would weigh wins and benefits
- When compared to gains, equivalent losses hurt more
- Pain and loss aversion is a more intense feeling than gain seeking
- This pehnomenon is consistent across regions and cultures
- To take advantage of this, framing each decision as loss aversion (loss framing) instead of gain seeking makes it more likely to be accepted
- Under time pressure, individuals will be more resolved to avoid losses
* 01.29.21
** Sagan Review
- If nuclear weapons were a norm,
  - conventional weapons would be preferred to nuclear weapons
  - this preference would not change even if the utility of nuclear weapons, when compared to conventional weapons, increased
- Cricially, Sagan finds that although Americans prefer conventional weapons when presented a choice, a large proportion are willing to approve of a nuclear strike after the fact
- The fraction of people that approved a nuclear strike grew with its effectiveness, indicating that perceptions towards nuclear use is based on nuclear utility
- There is no significant domestic political constraint on nuclear weapon usage
- Vast majority of people focused on utility to make their decision on nuclear weapons, with few focusing on moral factors
* 01.27.21
** Norms & Nukes
- Norms and taboos have been critical in nuclear policy
- Norms and taboos have changed our definition of nuclear weapons as solely a means of deterrence to something that is more feasible in small-scale war (through more tactical nuclear weapons)
** Norms & Taboos
- Cognitive constructs designed to guide our behavior
- Generally exist in the context of societal interaction and behavior
*** Norms
- Do's and Dont's
  - prescribe some behavior and deter other behaviors
- Context-specific
  - e.g killing is generally considered something that is horrible to do, but is just
- Large cultural variation in norms
- Consequences for violation of norms can vary significantly
*** Taboos
- Dont's - never explain things you should do, only address things you shouldn't
- Tend to be universal, with limited exception
- Significantly more limited variation, easier to translate across cultures
- There tend to be very severe consequences to taboo violations
** Norms, Taboos, and Decision-Making
- Generally, norms and taboos take certain strategies off the table and constrain the incentive structure
- Taboos and Norms also change our win-sets because of norms and taboos that exist in their own societies
- When the government needs to violate taboos or norms, they (1) argue that they aren't, through some loophole, and (2) argue that the benefits outweigh the harms
- To erode a norm, infuse it with consequentialist logic
* 01.21.21
** Public Opinion & Decision-Making
- domestic decision-making has significant foreign policy effects
- domestic public opinion has an effect on foreign policy decisions
  - public opinions can help shape the incentive structure that a decision-maker has when faced with a decision
  - public opinion can either be an opportunity or a cosntraint
- who we listen to and what they say can intrinsically change our incentive structure
** Putnam Review
- For any foreign policy issue, there is a chief of government (CoG)
  - CoG has ultimate decision-making authority on the issue
  - e.g, president on war, secretary for commerce on tariffs, etc.
- CoG's job is to find a way to align their international goals with what's possible domestically
  - This is the two-level game, domestic and international balances
- "Win-Set" defines the set of acceptable outcomes that is affected by the policy
  - "Win-Set" defined by war and peace is the entire US population
  - "Win-Set" defined by shoe-lace imports is extremely small
- Veto power must be considered
- Assumes a rational actor analysis
- While this applies largely to democratic states, the same general principles can also appply to authoritarian regimes
* Putnam
** Domestic-International Entanglements
- Current literature lists domestic influences on foreign policy and theorizes about links between the two
- Deutsch and Haas theorize about the impact of parties and interest groups on spillover from domestic policy to international objectives
- Recent work has focised on structural factors such as state strength causing an effect on foreign economic policy
  - central decision-makers must be concerned with domestic and international factors simultaneously
  - theory does not properly explain differences in state foreign policy occurring despite static state structures
** Two-level Games
- Politics of international negotiations can often be considerd a two-level game
  - At the national level, domestic groups pressure governemnt, politicians seek power through the the favor of those organizations
  - At the international leve, governments seek to minimize harms, maximize ability to solve domestic pressures
- Creates a very complex, sometimes contradictory situation for actors at both boards (decision-makers)
** Win-Sets
- Negotiation occurs at a 2-stage process:
  - Level 1: bargaining between negotiators leading to tentative agreement
  - Level 2: Separate discussions within each group about ratification
- In reality, process is not always linear - generally happens multiple times in multiple stages at multiple levels
- Larger win-sets make Level 1 agreement more likely
- The relative size of the respective level 2 win-sets will affect the distribution of the joint gains from the international bargain (the larger the win-set of actor 1, the more he can be pushed around by other actors)
** Win-Set Determinants
- Three factors critical to win-set size
  - Level 2 preferences and coalitions
  - Level 2 institutions
  - Level 1 negotiation strategies
** Uncertainty and Bargaining
- Level 1 negotiators are often badly misinformed about elvel 2 politics, especially on the opposing side
- Uncertainty about win set size can be both good and bad in 2 level negotiations
- Each bargainer has an incentive to understate his own win-sets
- Uncertainty about opponent's win set increases concern about risk of involuntary defection by the other side
** Role of the Chief Negotiator
- Chief negotiator is the only formal link between level 1 and 2 of negotiation
- Assumed that chief negotiator has no independent policy views, acts merely as an honest broker on behalf of his constitutents
- Motives of the chief negotiator:
  - enhancing level 2 game by having benefits outweigh harms as much as possible
  - shifting balance of power at level 2 in favor of his own person domestic policies
  - pursuing his own conception of national interest in the international sense
 - Also assumed that the chief negotiator has some sort of veto power to outright reject anything that wholly contradicts his personal beliefs

* Fearon
** Introduction
- Three reasons war may occur
  - People are sometimes irrational and don't consider the costs of war due to this irrationality or their biases
  - Leaders may enjoy benefits of war but not pay the costs
  - People are rational and consider the risks but fight anyway (Rationalist explanation)
- Flaws with contemporary rationalist arguments are that they don't address prewar bargains
- Contemporary Rationalist reasons for war:
  - Anarchy
  - Benefits o/w costs
  - Rational preventitive war
  - Rational miscalculation due to lack of info
  - Rational miscalculation due to diagreement about relative power
- Fearon's reasons for war
  - private or misrepresented info about relative capabilities
  - relationships are not possible because at least one party has an incentive to cheat
  - Despite being able to compromise, one or more party does not want to because of their beliefs on the issue
** The Puzzle
- People often see war as something nobody wants though wars can often simply be costly but worthwhile gambles
- Wars are always ex post inefficient because no matter how small, the costs of fighting still exist
** Anarchy
- War occurs because there is nothing to prevent it
- Does not explain why wars still occur due to their inefficiency, therefore does not explain war completely
- Anarchy may lead to arms races and insecurity, but little war outside or preemptive war
** Preventive War
- If a declining power suspects that it may be attacked in the future by a rising power, it will find a preventive war rational
- Theory does not consider diplomacy and timeframe
- Why should the declining power fear an attack if it's inefficient, even for the rising power
** Positive Expected Utility
- Argues that war is rational when both sides have a positive expected utility from it
- While often presented, this argument doesn't explain specific condition in which both parties fighting a war have positive expected utility
** Utility and Rationality
- Positive expected utility alone is not enough to provide a rationalist explanatino for war
- Indivisibility of factors of war can also be a rational explanation of war
** War and Private information
- War is often the product of rational miscalculation
- Leaders overestimate their chance of military victory
- State lack information about other side's willingness to fight
- Truly rational agents will make the same prediction about the outcome of an uncertain event when given the same set of facts
  - This does not happen when miscalculation occurs, which leads to war
- There also exist incentives to misrepresent in bargaining
- Combination of private info about relative power or will to fight and strategic incentive to misrepresent positions in baragaining constitute a rational explanation of war
** War & Commitment Problems
- With anarchy, states become suspicious of one another and build weapons and engage in attacks
- Anarchy matters when it seems as if a states preferences and opportunities for action imply that one or both sides in a dispute have incentives to renege on peaceful bargains which would be mutually preferable to war
- Preemptive war is one such case where if one wants to go to war, doing so stealthily would be the most save. While both parties would prefer to live in peace, they are constantly afraid of doing so because of the anarchic state of internaitonal affairs
  - Seems to work similar to the prisoner's dilemm
- The same principle can be applied to preventive war, lack of trust is not the driving factor behind war in these instances. Rather, circumstances that give one party an incentive to renege are
** Conclusion
- Because fighting is costly and risky, rational actors should prefer negotiations to war
- Rational actors may be unable to agree on these negotiations because
  - private information about resolve and capability, and the incentives that exist to misrepresent these
  - inability to commit to hold ip a deal
- Not arguing irrelevance for empirical studies concluding that war is based on irrationality
* 01.22.21
** Calculating Costs of War
*** Constants
- Fight occurs over $100
- Cost of war: $20
- P(Winning): 50%
*** Expected Value
- (Gains Winning) + (Gains Fighting) - (Cost of War)
- (0.5 \times 100) + (0) - (1 \times 20) = 50 - 20 = $30
- Because each side could negotiate in order to get an expected value of 31 <, it is not a rational deciison to go to war
*** Miscalculation
- When both sides overestimate the probability of winning, their expected value goes up, thereby making their minimum threshold for negotiation too high for the other side.
- Consider miscalculation wherein both sides believe they have an 80% probability of winning:
  - EV_{war} = (0.8 \times 100) + (0) - (1 \times 20) = 80 - 20 = 60.
  - Both sides therefore want an expected value of > 60, which is impossible given the limited value of the thing being fought over
* 01.20.21
** Rational Decision-Making
- Rational decision-making defines how we make decisions
- A person's or institutions goal is not relevant, the process of pursuing that goal is the factor driving decision-making
- This allows us to generalize decision-making significantly more
- Critical to consider the probabilistic nature of benefits and harms when considering rational decision-making
- Expected Value = "weighted value" for all costs and benefits
  - Same thing as "average payoff"
** Incentive Structures
- Incentive structures are the expected values for each of the strategies considered
- Incentive structures impose a certain course of action upon us, given that we are rational actors
* Expected Profit Khan
- Expected value can be calculated as the sum of all the outcome probabilities multiplied by their corresponding profits.
- Considering all outcome probabilities should yeild a total probability sum of 1 (100%), with profits being positive (gains) or negative (losses)
* 01.15.21
- Brain has a complex set of structures that work together to do both really important, and fundamentally flawed actions
** Brain Stem
- The reptilian brain
- Really just an extensino of the spinal cord
- Controls automatic actions, no effect on decision-making
** Middle Brain (Limbic System)
- Body's monitoring system to identify important elements of the environment
- Discriminates things of importantance constantly and ambiently
** Brain Cortex
- Controls higher-level thinking
- Moral decision-making, learning, conscious awareness
** Hierarchy of the brain
- Information goes from the brain stem, to the limbic system, to the brain cortex
- Critically, the limbic system was never designed to collect all the information around you - that incomplete information is used for decision-making
- Understanding the interplay and potential biases of the limbic system can help us understand decision-making and prevent bad decision making
- Fear and the triggering of fear prevents higher-level decision making and can prevent the intake of new information
- Sources of information can also have a significant effect on the processing of that information - can be seen through in-group/out-group bias
** Rational Decision-Making
1. Pick a goal
2. Evaluate all strategies
   - Analyze costs
   - Analyze benefits
3. Select strategy with best cost/benefit ratio
- Bias often occurs at stage 2 because of filtration of information through the limbic system

* Notes Config
# Web Export Config
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="rethink.css" />
#+OPTIONS: toc:nil num:nil html-style:nil
