#+TITLE: Strategic Intelligence
#+AUTHOR: Sudhan Chitgopkar
#+EMAIL: sudhanchitgopkar@uga.edu
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="rethink.css" />
#+OPTIONS: toc:nil num:nil html-style:nil

* Critiques of the Intelligence Cycle
- Hulnick argues that while the intelligence model is basic, it is inherently flawed because it isn't accurate
- Regarding analysis, Hulnick finds that there is a disconnect between field officers and analysts, which is caused by lack of communication, cooperation, or mishandling of information
* Intelligence Cycle
- Decision-makers are expected to make the best-decision possible, and the intelligence cycle explains how intelligence is developed to give decision-makers the information they need
- Components of the Intelligence Cycle
  - Planning and Direction
  - Collection
  - Processing
  - Analysis
  - Dissemination
** Planning and Direction
- Policy-makers request intelligence on a particular subject or target
- 3 subcategories
  - Task Definiton - primary jumping off point
  - Analysis and formulation - consider all possible facets of the task, potential sources and challenges, and formulating the best plan. Very creative and challenging process. Critical to consider the specifics of the question and understand specifically what is requested from the customer/decision-maker
  -  Core planning - allocation of finances, employees, and resources before the actual intelligence process can go underway. Specific steps and deadlines are also set up here.
** Collection
- Collection of raw information and intelligence
- Draws on a variety of different types of information collection methods
- Can come from a variety of different means (human, physical, technological, social media, etc.)
** Processing
- Pre-analytical filtering
- Collation refers to steps taken to turning raw data into something that may be analyzed, can also refer to proper organization. Transforming data into a readable state
- Evaluation - combing through information to provide a credibility and validity scale to determine accuracy/reliability of information.
  - Grading systems are used A-F, 1-6 to grade reliability of each sources
  - Grade determines the weight assigned to it
  - Evaluation also allows for security clearance can be derived for that information
** Analysis
- Analysts are generally subject matter experts and are tasked with creating a cohesive story with all of the information
- Creation of written reports occurs here
** Dissemination
- Distribution of final information and reports, leading to decisions and more intelligence tasks
** Critiques
- Cycle is over-simplified, doesn't account for specific types of intelligence collection or specifics of what policy-makers may want
- Overly linear, process is much more complex and this is a simplistic representation. Furthermore, some stages can be started before others are done, states of the cycle are not discrete
** Additional Steps
- Some argue that consumption should be included in the cycle. Disemmination is not the end of the cycle, the way in which information is consumed should be considered because of the effects that has on decision-making
- Feedback may also be important to consider because of a continuous loop of feedback during and after the process is beind completed
- Counter-intelligence and covert action not addressed by this cycle, which gives an incorrect understanding of contemporary intelligence operations
** Additional Questions
- Does the cycle's past affect its current use?
- Should the cycle be refined?
  - If so, how?
  - If not, what is the purpose of the cycle
    - purely academic?
    - barebones basics?
* Johnson
** Introduction
- Intelligence is defined as a set of activities carried out by government agencies that operate largely in secret including collection and interpretation of information from a mixture of open and clandestine sources to arrive at a product useful to illuminate foreign policy deliberations
- These agencies also engage in covert action and manipulate events abroad
** The Intelligence Cycle
- describes the flow of activities for collection and analysis of info
- not generally considered a defined cycle, rather considered a complex matrix of interactions
- 5 stages
  - planning and direction
  - collection
  - processing
  - production and analysis
  - dissemination
** Planning and Direction
- intel managers and policy officials must decide what data should be gathered
- determine what the most critical information to policy-making is
- scope = breadth of intelligence tasks
- paradoxically, more wealthy nations are more likely to have information failures
- The more affluent and globally oriented a nation, the larger its agenda of intelligence objectives and its institutional apparatus for espionage, and the more
  likely its chances for a large number of successes as a result of this saturated
  world coverage. For the same reason, they are more likely to experience international failures as they have very large global objectives.
- As policymakers focus their informational needs and objectives, the chances of relevant intelligence successes increases
** Collection
* Turner
** US Intelligence
- While US intelligence is not funadmentally unique, it has a series of norms that make it very distinctive
- Realism has been the dominant theory explaining intelligence gathering and behavior
- Much of the US approach to intelligence takes from strategic culture, creating the US intelligence identity
** Constructivism
- Constructivists see intelligence as highly malleable, made up of historical processes, accepted behavior, and contemporary beliefs and interests
** American Strategic Culture
- While American culture and opinion is very varied, there are central themes defining strategic intelligence
- 3 influences shape americans view of national security
  1. lack of a sense of history
     - leads to a positive, successful image of thesmselves
  2. unique geography
     - historical isolationism, general security, significant resources
  3. Anglo-saxon heritage
     - aversion to/suspicion of military and attachment to constitutionalism
** Distinguishing Norms
- Institutional Survival - all intelligence agencies are bureaucracies trying to maximize resources and funding in the political marketplace
- Secrecy - conflicts with American belief in the transparency of government, is foundational to the USIC, has lef to abuse and problems
- Exceptionalism - occurs because of (1) secrecy, (2) breaking other country's laws, (3) subject to deception and disinformation, and (4) intelligence is fungible and can be used by politicians for a wide variety of purposes
- Ambiguous Mandate - Mission has always been vague to fudge priorities and targets
- Confederal Structure - While americans oppose a strong central intelligence authority, fragmentation
- Competitive Intelligence - each bureau tries to compete with the other to increase innovation, eventually just ends up in redundancy and waste
- Flexible Accountability - Many systems are rooted in accountability but intelligence seems to often get a free pass on many missions
- Intelligence-Law Enforcement Separation - exists due to fear of combination and overpower (eg. Gestapo) and that intelligence is considered inherently different than law enforcement
- Separation of Intelligence from Policy - Many argue that for intelligence to be truly objective, it must be separated from policy.  Some argue that intelligence works best when it is in tuen with a policy-makers objectives
- Policy Support - due to the separation, intelligence is an area of the government. There is disagreement about how much intelligence should be used to support or advocate for a policy
- "Can Do" Attitude - optimism and risk-taking inherent to intelligence efforts
- Primacy of analysis - US has very significant amount of analysis capabilities, especially because of the role of intelligence on policy and decision-making in government
- "Accurate, timely, and relevant intelligence" - phrase has become a mantra within USIC and shows main principles of intelligence work
** Road to Failure
- Norms of USIC indicate uncertainty about the role of intelligence in government and society
- US Intelligence is the product of political compromise and checks and balances, with certain positive qualities giving intelligence workers the tools necessary to do their job
- Many good and bad aspects to intelligence
- As a whole, intelligence identity of the US reflects the fact that people want intel to serve the national interest, but abide by the conutry's democratic princples - which eventually helps conduct important work but also sets up the intel community for failure in some cases.
* Warner
- No official definition for intelligence exists
** Intelligence Definitions
- National Security Act of 1947 defines foreign intelligence as "information relating to the capabilities, intentions, or activities of foreign governments or elements thereof."
- Hoover Commission 1955 define that "intelligence deals with all the things which should be jnown in advance of initiating a course of action"
- Brown-Aspin Commission defines that intelligence is "simply and boradly information about things foreign - people, places, things, and events - needed by the government for the conduct of its functions"
- Joint Chief if Staffs Dictionary of Military and Associated Terms defines it as "the product resulting from the collection, processing, integration, analysis, evaluation, and interpretation of available information concerning foreign countries or areas" or as "information and knowledge about an adversary obtained through observation, investigation, analysis, or understanding"
- CIA defines intelligence as "the knowledge and foreknowledge of the world around us - the prelude to decision and action by US policymakers"
** Definition Analysis
- Most definitions stress information over organization
- Defining intelligence simply as information is generally to broad for intelligence professionals to carry out their jobs
- Not every single peiece of information is intelligence
- Intelligence can then be considered both an action and a product
- Shulsky emphasizes the secret nature of this information as being a critical aspect of intelligence
** Final Steps
- Intelligence is then an activity and a product conducted through confidential circumstances on behalf of states so that policy-makers can understand foreign developments, and that it includes clandestine operations performed to cause certain foreign effects
- Difference between law enforcement and intelligence is secrecy
* Intelligence Structure
** What is Intelligence
- Process
- Activity - the actual job conducted by an individual or organization to obtain intelligence
- Final Product - the final report or analysis derived through the process of gaining intelligence that is eventually disseminated
- Elements of Intelligence
  1. Dependent on confidential sources and methods for full effectiveness
  2. Performed by officers of the state, for the state
  3. Focused on foreigners - usually other states, but often foreign subjects, corporations, or groups
  4. Linked to the production and dissemination of information
  5. Involved in influencing foreign entities through means that can't trace back to the acting government
- Concise Definition: Intelligence is secret, state activity to understand or influence foreign entities
** Levels of Analysis
- Strategic Intelligence - broad, policy-oriented approach to intelligence. Understands the effects of intelligence and international factors on the world
- Operational Intelligence - group-focused intelligence, understanding interplay between groups of people or institutions
- Tactical Intelligence - low-level intelligence focused on field scenarios and day-to-day operations of intelligence
** US Intelligence Community
*** Independent
- Office of the Director of National Intelligence (ODNI) - intermediary oversight agency consolidating all of the intelligence and pushing it to policy-makers
- Central Intelligence Agency (CIA) - Leading expert in clandestine operations for the US, uses their own paramilitary. Only independent agency that runs operations
*** Departments of Agencies
- Department of Energy Office of Intelligence and Counterintelligence (DOE-OIC) - leading experts in nuclear weapons, energy infrastructure, and security maintenance
- Department of Homeland Security's Office of Intelligence and Analysis - Domestic security focus
- FBI Intelligence Branch (FBIIB) - Focus on federal crimes and domestic security
- DEA Office of National Security Agency (DEAONSI) - focus on drugs and drug trade
- Department of Small Business Innovation Research (DOSBIR) - focused on diplomatic intelligence
- Dept of Treasury Intelligence Agency (USDTOIA) - understanding how the US dollar could be used in criminal activities
- US Coast Guard Intelligence (USCGI) - charged with keeping ports, waterways, cargo, and coasts safe
*** Department of Defense
- Defense Intelligence Agency (DIA) - DoD's version of the CIA, focused on troop movements, troop aquisitions
- National Security Agency/Central Security Service (NSA/CSS) - leading experts in signal communications and telecommunications
- National Geospatial Intelligence Agency (NGA) - focuses on GIS, geography
- National Reconnaissance Office (NRO) - one of the most secret agencies, existence wasn't acknowledged until the '50's, control spy sattelite network
- US Army Intelligence (USAI) - control field operations and movement of troops
- Office of Naval Intelligence (ONI) - control water-based troop movements, cargo movement, and political intelligence
- US Marine Corps Intelligence (USMCI) - provide tactical intelligence for troop movements through surge and occupancy operations, also provide counterintelligence consultation to the rest of the USIC
- US Air Force Intelligence, Surveillance, and Reconnaissance (USAFISR/16AF) - focus on imagery intelligence, security countermeasures, telecommunications

** Questions to Consider
- Do you agree with the concise definition of intelligence?
- Which level of analysis would you most focus on?
- Can you see the bureaucracy of the intelligence community helping or hurting its overall mission?
