#+TITLE: Strategic Intelligence
#+AUTHOR: Sudhan Chitgopkar
* Turner
- While US intelligence is not funadmentally unique, it has a series of norms that make it very distinctive
-
* Warner
- No official definition for intelligence exists
** Intelligence Definitions
- National Security Act of 1947 defines foreign intelligence as "information relating to the capabilities, intentions, or activities of foreign governments or elements thereof."
- Hoover Commission 1955 define that "intelligence deals with all the things which should be jnown in advance of initiating a course of action"
- Brown-Aspin Commission defines that intelligence is "simply and boradly information about things foreign - people, places, things, and events - needed by the government for the conduct of its functions"
- Joint Chief if Staffs Dictionary of Military and Associated Terms defines it as "the product resulting from the collection, processing, integration, analysis, evaluation, and interpretation of available information concerning foreign countries or areas" or as "information and knowledge about an adversary obtained through observation, investigation, analysis, or understanding"
- CIA defines intelligence as "the knowledge and foreknowledge of the world around us - the prelude to decision and action by US policymakers"
** Definition Analysis
- Most definitions stress information over organization
- Defining intelligence simply as information is generally to broad for intelligence professionals to carry out their jobs
- Not every single peiece of information is intelligence
- Intelligence can then be considered both an action and a product
- Shulsky emphasizes the secret nature of this information as being a critical aspect of intelligence
** Final Steps
- Intelligence is then an activity and a product conducted through confidential circumstances on behalf of states so that policy-makers can understand foreign developments, and that it includes clandestine operations performed to cause certain foreign effects
- Difference between law enforcement and intelligence is secrecy
* 01.20.20 (Intelligence Structure)
** What is Intelligence
- Process
- Activity - the actual job conducted by an individual or organization to obtain intelligence
- Final Product - the final report or analysis derived through the process of gaining intelligence that is eventually disseminated
- Elements of Intelligence
  1. Dependent on confidential sources and methods for full effectiveness
  2. Performed by officers of the state, for the state
  3. Focused on foreigners - usually other states, but often foreign subjects, corporations, or groups
  4. Linked to the production and dissemination of information
  5. Involved in influencing foreign entities through means that can't trace back to the acting government
- Concise Definition: Intelligence is secret, state activity to understand or influence foreign entities
** Levels of Analysis
- Strategic Intelligence - broad, policy-oriented approach to intelligence. Understands the effects of intelligence and international factors on the world
- Operational Intelligence - group-focused intelligence, understanding interplay between groups of people or institutions
- Tactical Intelligence - low-level intelligence focused on field scenarios and day-to-day operations of intelligence
** US Intelligence Community
*** Independent
- Office of the Director of National Intelligence (ODNI) - intermediary oversight agency consolidating all of the intelligence and pushing it to policy-makers
- Central Intelligence Agency (CIA) - Leading expert in clandestine operations for the US, uses their own paramilitary. Only independent agency that runs operations
*** Departments of Agencies
- Department of Energy Office of Intelligence and Counterintelligence (DOE-OIC) - leading experts in nuclear weapons, energy infrastructure, and security maintenance
- Department of Homeland Security's Office of Intelligence and Analysis - Domestic security focus
- FBI Intelligence Branch (FBIIB) - Focus on federal crimes and domestic security
- DEA Office of National Security Agency (DEAONSI) - focus on drugs and drug trade
- Department of Small Business Innovation Research (DOSBIR) - focused on diplomatic intelligence
- Dept of Treasury Intelligence Agency (USDTOIA) - understanding how the US dollar could be used in criminal activities
- US Coast Guard Intelligence (USCGI) - charged with keeping ports, waterways, cargo, and coasts safe
*** Department of Defense
- Defense Intelligence Agency (DIA) - DoD's version of the CIA, focused on troop movements, troop aquisitions
- National Security Agency/Central Security Service (NSA/CSS) - leading experts in signal communications and telecommunications
- National Geospatial Intelligence Agency (NGA) - focuses on GIS, geography
- National Reconnaissance Office (NRO) - one of the most secret agencies, existence wasn't acknowledged until the '50's, control spy sattelite network
- US Army Intelligence (USAI) - control field operations and movement of troops
- Office of Naval Intelligence (ONI) - control water-based troop movements, cargo movement, and political intelligence
- US Marine Corps Intelligence (USMCI) - provide tactical intelligence for troop movements through surge and occupancy operations, also provide counterintelligence consultation to the rest of the USIC
- US Air Force Intelligence, Surveillance, and Reconnaissance (USAFISR/16AF) - focus on imagery intelligence, security countermeasures, telecommunications

** Questions to Consider
- Do you agree with the concise definition of intelligence?
- Which level of analysis would you most focus on?
- Can you see the bureaucracy of the intelligence community helping or hurting its overall mission?
